{% set name = "piccolo-theme" %}
{% set version = "0.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/piccolo_theme-{{ version }}.tar.gz
  sha256: e30f20c8e829b3e0d69a891a2443d0e77d077e3450fe18447bb9a19d490d31f7

build:
  number: 0
  noarch: python
  script:
    - rm -f pyproject.toml
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - setuptools >=42
    - python >=3.7
  run:
    - python >=3.7
    - sphinx

test:
  imports:
    - piccolo_theme
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/piccolo-orm/piccolo_theme
  summary: A modern Sphinx theme.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - moorepants
