{% set name = "piccolo-theme" %}
{% set version = "0.24.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/piccolo_theme-{{ version }}.tar.gz
  sha256: 09cf70f4bb6dba4ebcd14966550c292339c11d931c9533221cd3dbffeb1d1bd9

build:
  number: 1
  noarch: python
  script:
    - rm -f pyproject.toml
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - setuptools >=42
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - sphinx

test:
  imports:
    - piccolo_theme
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/piccolo-orm/piccolo_theme
  summary: A modern Sphinx theme.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - moorepants
