{% set name = "piccolo-theme" %}
{% set version = "0.15.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/piccolo_theme-{{ version }}.tar.gz
  sha256: f15c64af3003a77c8279bd36071b53ea848fd45097f065b8a1ce8e1022b6849c

build:
  number: 0
  noarch: python
  script:
    - rm -f pyproject.toml
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - setuptools >=42
    - python >=3.7
  run:
    - python >=3.7
    - sphinx

test:
  imports:
    - piccolo_theme
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/piccolo-orm/piccolo_theme
  summary: A modern Sphinx theme.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - moorepants
